# 定义 Workflow 的名字
name: Greeting from Mona

# 定义 Workflow 的触发器
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'Triggered when a tag is selected'
        required: true
        type: string

# 定义 Workflow 的 job
jobs:
  # 定义 job 的 id
  my-job:
    # 定义 job 的 name
    name: My Job
    # 定义 job 的运行环境
    runs-on: ubuntu-latest
    # 定义 job 的运行步骤
    steps:
      # 定义 step 的名称
      - name: Print a greeting
        # 定义 step 的环境变量
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        # 运行指令：输出环境变量
        run: |
          echo ${{ github.action_ref }}
